version: '3.8'

services:
    database:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=payment
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - payment-network

volumes:
    postgres_data:

networks:
    payment-network:
